#!/usr/bin/env python3
"""Generate skills.yaml manifest from SKILL.md frontmatter files."""
from __future__ import annotations

import sys
from pathlib import Path

import yaml

# Add parent dir so we can reuse parse_frontmatter
REPO_ROOT = Path(__file__).resolve().parent.parent
SKILLS_DIR = REPO_ROOT / "skills"
MANIFEST_PATH = REPO_ROOT / "skills.yaml"


def parse_frontmatter(content: str) -> dict[str, str]:
    """Parse YAML frontmatter from SKILL.md content.

    Reuses the same regex-free approach: split on '---' delimiters.
    """
    import re

    match = re.match(r"^---\s*\n(.*?)\n---\s*\n", content, re.DOTALL)
    if not match:
        raise ValueError("No valid YAML frontmatter found")
    return yaml.safe_load(match.group(1))


def extract_version(meta: dict[str, str]) -> str:
    """Extract version from metadata.version (preferred) or top-level version (legacy)."""
    metadata = meta.get("metadata")
    if isinstance(metadata, dict) and metadata.get("version"):
        return str(metadata["version"])
    return str(meta.get("version", ""))


def collect_skills() -> list[dict[str, str]]:
    """Walk skills/*/SKILL.md and build manifest entries."""
    entries: list[dict[str, str]] = []

    for skill_dir in sorted(SKILLS_DIR.iterdir()):
        skill_md = skill_dir / "SKILL.md"
        if not skill_dir.is_dir() or not skill_md.exists():
            continue

        content = skill_md.read_text(encoding="utf-8")
        meta = parse_frontmatter(content)

        name = meta.get("name", "")
        version = extract_version(meta)
        description = meta.get("description", "")

        if not name:
            print(f"WARNING: {skill_md} missing 'name' field, skipping", file=sys.stderr)
            continue

        if not version:
            print(f"WARNING: {skill_md} missing 'version' field, skipping", file=sys.stderr)
            continue

        entries.append({
            "name": name,
            "version": version,
            "description": description.strip() if description else "",
            "path": str(skill_dir.relative_to(REPO_ROOT)),
        })

    return entries


def write_manifest(entries: list[dict[str, str]]) -> None:
    """Write skills.yaml manifest file."""
    manifest = {"skills": entries}
    header = "# Auto-generated by scripts/generate_manifest.py — do not edit manually.\n"

    with MANIFEST_PATH.open("w", encoding="utf-8") as f:
        f.write(header)
        yaml.dump(
            manifest,
            f,
            default_flow_style=False,
            sort_keys=False,
            allow_unicode=True,
            width=120,
        )

    print(f"Generated {MANIFEST_PATH} with {len(entries)} skills")


def main() -> int:
    """Generate skills.yaml from SKILL.md frontmatter."""
    entries = collect_skills()
    if not entries:
        print("ERROR: No skills found", file=sys.stderr)
        return 1

    write_manifest(entries)
    return 0


if __name__ == "__main__":
    sys.exit(main())
